Feature/CambioInsertarMovimientos
udistrital/movimientos_crud pull request #121
Opened 2022-07-11 01:01 UTC by brayanpasa99

Trata: udistrital/financiera_documentacion#444

2022-07-11 02:49 UTC, AlexFBP requested changes
Comentarios respecto a control de errores y a un helper que es necesario crear

2022-07-11 02:49 UTC, AlexFBP commented on controllers/movimiento_detalle.go
> +	defer errorctrl.ErrorControlController(c.Controller, "CrearMovimientosDetalle2")
(En los controller) Va el nombre del controlador
```suggestion
	defer errorctrl.ErrorControlController(c.Controller, "MovimientoDetalleController")
```

2022-07-11 02:49 UTC, AlexFBP commented on controllers/movimiento_detalle.go
> +		panic(errorctrl.Error("CrearMovimientosDetalle2 - json.Unmarshal(c.Ctx.Input.RequestBody, &movimientosDetalle)", err, "404"))
Acá iría el nombre de la función
```suggestion
		panic(errorctrl.Error("InsertarMovimientosDetalle - json.Unmarshal(c.Ctx.Input.RequestBody, &movimientosDetalle)", err, "404"))
```

2022-07-11 02:49 UTC, AlexFBP commented on controllers/movimiento_detalle.go
> +	}
Mover todo esto a un helper, digamos, en la carpeta/`package` helpers:...
```go
package helpers

func InsertarMovimientosDetalle(movimientosDetalle []models.MovimientoDetalleInsertar)
(movimientosRespuesta []models.MovimientoDetalle,
outputError map[string]interface{}, // <-- Agregar esta propiedad si se implementa el control de errores
) {
  // Recomendado: Implementar el control de errores, preferentemente manejarlo
  // como una transacción: O se hacen todas o ninguna

  // Como mínimo, el código de las L352-380:
  for ... {
  }
}

2023-02-13 22:00 UTC, brayanpasa99 commented
Se cierra dado que ya no tengo vinculación con la organización

2023-02-13 22:00 UTC, closed without merging