Feature/insertar entradas hu
udistrital/movimientos_crud pull request #74
Opened 2020-12-28 21:47 UTC by CristianDavidSanchez

feature:  Se inserta por migración  los campos de las nuevas entradas registradas por la historia de usuario udistrital/arka_cliente#368

2020-12-28 22:23 UTC, BOTOOM requested changes
se solicitan cambios

2020-12-28 22:23 UTC, BOTOOM commented on database/files/inserts_entradas_tipo_movimiento.down.sql
> +DELETE FROM movimientos.tipo_movimiento;
si la migración falla no puede eliminarme la tabla así que o realiza otra acción o se quita el archivo de down, ya que si elimina la tabla elimina todos los registro ya existentes

2020-12-28 22:23 UTC, BOTOOM commented on database/migrations/20201227_122713_insertar_tipo_movimiento_entradas_nuevas.go
> +func (m *InsertarTipoMovimientoEntradasNuevas_20201227_122713) Down() {
si se quita el sql de down esta función quedara vacía o se borra

2020-12-28 22:23 UTC, BOTOOM commented on database/files/inserts_entradas_tipo_movimiento.up.sql
> +INSERT INTO movimientos.tipo_movimiento (id, nombre, descripcion, acronimo, activo)VALUES (29, 'Caja menor', 'Entrada por adquisicion por caja menor', 'e_arka', true);
se que las anteriores migraciones tenían los id que se ingresan de cada registro pero si el id es la PK no es necesario colocar el id y es mala practica, porfa elimina los números id de los insert

2020-12-29 00:03 UTC, CristianDavidSanchez commented on database/files/inserts_entradas_tipo_movimiento.up.sql
> +INSERT INTO movimientos.tipo_movimiento (id, nombre, descripcion, acronimo, activo)VALUES (29, 'Caja menor', 'Entrada por adquisicion por caja menor', 'e_arka', true);
lo intente eliminando los numeros pero la migración nunca corre, cuando lo pase a pgmodeler es como si el campo de la tabla correspondiente no estuviese definido como un serial si no como in entero.  supongo que por eso pusieron los inserts con el campo del id.

2020-12-29 00:08 UTC, CristianDavidSanchez commented on database/files/inserts_entradas_tipo_movimiento.up.sql
> +INSERT INTO movimientos.tipo_movimiento (id, nombre, descripcion, acronimo, activo)VALUES (29, 'Caja menor', 'Entrada por adquisicion por caja menor', 'e_arka', true);
aparece el error de que la primary key no puede repetirse  cuando se intenta la migración.

2020-12-29 00:11 UTC, BOTOOM approved these changes

2020-12-29 00:12 UTC, merged