Feature/campo detalle ajuste modelo
udistrital/movimientos_crud pull request #95
Opened 2021-11-20 05:02 UTC by brayanpasa99

Según la reunión realizada, se realizan ajustes al modelo de datos y sus respectivos cambios en cógido a la API

Tiene que ver con: udistrital/presupuesto_cliente#468

2021-11-20 05:15 UTC, AlexFBP requested changes
En general bien. Aparte de un comentario menor con un *suggested change* incluido; porfa hacer un pequeño retoque del svg con [inkscape](https://inkscape.org/es/), [actualmente](https://github.com/udistrital/movimientos_crud/blob/0ebd23da979a88fa8e619a3e7e4e99674f2c7dab/database/movimientos.svg) se ve así:
![image](https://user-images.githubusercontent.com/6588872/142715323-af11d0aa-1144-4ce4-8a44-f99fdabb17f3.png)

2021-11-20 05:15 UTC, AlexFBP commented on database/files/20211119_233423_agregarcampoDetalle_movimiento_detalle_down.sql
> +ALTER TABLE movimientos.movimiento_detalle DROP COLUMN IF EXISTS detalle;
(En general) Dejar la última línea de cualquier archivo de texto plano seguido por Git, vacía, sin espacios ni nada
```suggestion
ALTER TABLE movimientos.movimiento_detalle DROP COLUMN IF EXISTS detalle;

```

2021-11-21 00:05 UTC, brayanpasa99 commented
Con base en las nuevas observaciones encontradas se realizan las modificaciones para ajustar las fechas y agregar los registros correspondientes para la adición y reducción de lo denominado Cuentas Presupuestales

2021-11-21 16:33 UTC, AlexFBP requested changes
- En general, dejar vacía la última línea de cualquier archivo de texto plano seguido por Git
- En general, donde haya condiciones de error y/o alertas, críticas, etc; donde sea pertinente, no escatimar en logs, dado que son la única forma que tenemos de saber qué está pasando o pasó

2021-11-21 16:33 UTC, AlexFBP commented on database/files/20211120_140153_default_dates_up.sql
> +EXECUTE PROCEDURE trigger_set_fecha_creacion();
(En general) Dejar la ultima linea vacía de cualquier archivo de texto plano seguido por Git
```suggestion
EXECUTE PROCEDURE trigger_set_fecha_creacion();

```

2021-11-21 16:33 UTC, AlexFBP commented on database/files/20211120_140153_default_dates_down.sql
> +DROP FUNCTION trigger_set_fecha_creacion() cascade;
```suggestion
DROP FUNCTION trigger_set_fecha_creacion() cascade;

```

2021-11-23 19:41 UTC, AlexFBP requested changes

2021-11-23 19:41 UTC, AlexFBP commented on main.go
> +	// auditoria.InitMiddleware()
```suggestion
	auditoria.InitMiddleware()
```

2021-11-24 00:04 UTC, AlexFBP approved these changes

2021-11-24 00:04 UTC, merged